services:

  app-logic:
    build: .
    container_name: backend_app
    expose:
      - "3001"
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://host.docker.internal:27017/pedidos

  web-server:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
      - "8443:443"   # 🔥 HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/nginx/certs/cert.pem:ro
      - ./key.pem:/etc/nginx/certs/key.pem:ro
    depends_on:
      - app-logic